# General configurations
seed: 0

# Path configurations
save_path: 'output'
config_file: ''
model_file: ''

# Train configurations
num_epochs: &num_epochs 20
train_batch_size: 64
test_batch_size: 64
num_workers: 4
print_freq: 50
save_freq: 1
evaluate: True

scheduler:
  type: 'StepDecay'
  learning_rate: 0.001
  step_size: 15
  gamma: 0.1
  num_epochs: *num_epochs

optimizer:
  type: 'Adam'
  weight_decay: 0.0001

model:
  type: 'LeNet'
  act: 'ReLU'
